---
- name: Build transmission image
  docker_image:
    name: haugene/transmission-openvpn
    force: yes

- name: Create transmission data dir
  file:
    path: "{{ transmission_data_path }}"
    state: directory

- name: Create transmission /config dir
  file:
    path: "{{ transmission_data_path }}/config"
    state: directory

- name: Create transmission /data dir
  file:
    path: "{{ transmission_data_path }}/data"
    state: directory

- name: Delete transmission container
  command: docker rm --force transmission
  ignore_errors: yes

- name: Create transmission container
  command: >-
    docker run
    --detach
    --env OPENVPN_PASSWORD={{ vault_openvpn_password }}
    --env OPENVPN_PROVIDER=NORDVPN
    --env OPENVPN_USERNAME={{ vault_openvpn_username }}
    --env TRANSMISSION_RATIO_LIMIT=0
    --env TRANSMISSION_RATIO_LIMIT_ENABLED=true
    --mount src='{{ transmission_data_path }}/config',target=/config,type=bind
    --mount src='{{ transmission_data_path }}/data',target=/data,type=bind
    --name transmission
    --publish 9091:9091
    --restart unless-stopped
    haugene/transmission-openvpn
