alias: Turn off lights when Ryan leaves network
trigger:
  platform: state
  entity_id: device_tracker.ryan_nexus_5x
  from: home
  to: not_home
action:
  service: light.turn_off
  data:
    entity_id: light.bedroom
