version: "3.7"
services:
  ansible:
    container_name: ansible
    build:
      context: .
      dockerfile: Dockerfile
      args:
        target_address: ${target_address}
        target_host_ansible_name: ${target_host_ansible_name}
        target_host_os_model: ${target_host_os_model}
