version: "3.7"
services:
  ansible:
    container_name: ansible
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "ansible_vault_password=${ansible_vault_password}"
        - "target_address=${target_address}"
        - "target_host_ansible_name=${target_host_ansible_name}"
        - "target_host_os_model=${target_host_os_model}"
    volumes:
      # TODO remove this
      - type: bind
        source: "./ansible/helper"
        target: "/helper"

# TODO clean up all docker-compose files to use
# args | environment:
#   KEY: value
