# TODO ansible sub task of homeassistant_init

- name: Copy .profile to homeassistant home
  copy:
    src: .profile
    dest: "{{ homeassistant_home_path }}"

- name: Install bluetooth
  apt:
    name: bluetooth
    state: latest
    install_recommends: no

- name: Install libglib2.0-dev
  apt:
    name: libglib2.0-dev
    state: latest
    install_recommends: no

- name: Install pkg-config
  apt:
    name: pkg-config
    state: latest
    install_recommends: no

- name: Install libboost-python-dev
  apt:
    name: libboost-python-dev
    state: latest
    install_recommends: no

- name: Install libboost-thread-dev
  apt:
    name: libboost-thread-dev
    state: latest
    install_recommends: no

- name: Install libbluetooth-dev
  apt:
    name: libbluetooth-dev
    state: latest
    install_recommends: no

- name: Install libcap2-bin
  apt:
    name: libcap2-bin
    state: latest
    install_recommends: no

- name: Delete gattlib repo in tmp
  file:
    path: "{{ gattlib_tmp_repo_path }}"
    state: absent

- name: Clone gattlib repo to tmp
  git:
    repo: https://github.com/rhoriguchi/gattlib.git
    dest: "{{ gattlib_tmp_repo_path }}"
    version: ev3dev-stretch/0.20150805-1ev3dev2

- name: Replace 'src/ with './src/ in gattlib setup.py
  replace:
    path: "{{ gattlib_tmp_repo_path }}/setup.py"
    regexp: "'src[/](?!bluez')"
    replace: "'./src/"

- name: Replace boost_python-py34 with boost_python-py35 in gattlib setup.py
  replace:
    path: "{{ gattlib_tmp_repo_path }}/setup.py"
    regexp: "boost_python-py34"
    replace: "boost_python-py35"

- name: Replace boost_python-py34 with boost_python-py35 in gattlib Makefile
  replace:
    path: "{{ gattlib_tmp_repo_path }}/src/Makefile"
    regexp: "boost_python-py34"
    replace: "boost_python-py35"

- name: Replace boost_python-py34 with boost_python-py35 in gattlib bump-python-boost-library-to-3.5
  replace:
    path: "{{ gattlib_tmp_repo_path }}/debian/patches/bump-python-boost-library-to-3.5"
    regexp: "boost_python-py34"
    replace: "boost_python-py35"

- name: Pip install gattlib
  pip:
    name: "{{ gattlib_tmp_repo_path }}"
    virtualenv: "{{ homeassistant_virual_env_path }}"

- name: Install gatlibb to homeassistant virtualenv
  command: "python3 {{ gattlib_tmp_repo_path }}/setup.py install"

# TODO ansible run this command
# sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3\``
