---
- name: Create glances data dir
  file:
    path: "{{ data_path.library.glances }}"
    state: directory

- name: Generate glances glances.conf with correct values
  template:
    src: glances.conf.jinja2
    dest: "{{ data_path.library.glances }}/glances.conf"

- name: Delete glances docker-compose dir
  file:
    path: "{{ data_path.library.docker_compose.glances }}"
    state: absent

- name: Create glances docker-compose dir
  file:
    path: "{{ data_path.library.docker_compose.glances }}"
    state: directory

- name: Delete glances dir in glances docker-compose dir
  file:
    path: "{{ data_path.library.docker_compose.glances }}/glances"
    state: absent

- name: Clone glances to glances docker-compose dir
  git:
    repo: https://github.com/nicolargo/glances.git
    dest: "{{ data_path.library.docker_compose.glances }}/glances"

- name: Copy Dockerfile to glances docker-compose dir
  copy:
    src: "{{ role_path }}/files/Dockerfile"
    dest: "{{ data_path.library.docker_compose.glances }}"
    force: yes

- name: Set glances options
  set_fact:
    glances_options: "--webserver"

- name: Generate docker-compose.yaml with correct values
  template:
    src: docker-compose.yaml.jinja2
    dest: "{{ data_path.library.docker_compose.glances }}/docker-compose.yaml"

- name: docker-compose up
  command: docker-compose up --build --detach --force-recreate --remove-orphans
  args:
    chdir: "{{ data_path.library.docker_compose.glances }}"
