---

# TODO external drive not showing

- name: Generate glances.conf with correct values
  template:
    src: glances.conf
    dest: "{{ role_path }}/files/glances.conf"

- name: Build glances image
  docker_image:
    name: rhoriguchi/glances
    path: "{{ role_path }}/files"
    buildargs:
      alpine_version: "{{ alpine_version }}"
      python_version: "{{ python_version }}"

- name: Delete glances.conf
  file:
    path: glances.conf
    state: absent

# TODO commented

# - name: Set glances server options
#   set_fact:
#     glances_options: "--webserver --password --server"
#     glances_docker_container_name: glances-server
#   when: glances_mode == "server"
#
# - name: Set glances client options
#   set_fact:
#     glances_options: "--webserver --password --client xxlpitu-home.duckdns.org"
#     glances_docker_container_name: glances-client
#   when: glances_mode == "client"

- name: Set glances options
  set_fact:
    glances_options: "--webserver"
    glances_docker_container_name: glances

- name: Delete glances container
  shell: "docker rm --force {{ glances_docker_container_name }}"
  ignore_errors: yes

- name: Create glances container
  shell: >-
    docker run
    --detach
    --env GLANCES_OPT='{{ glances_options }}'
    --mount src=/var/run/docker.sock,target=/var/run/docker.sock,type=bind
    --name '{{ glances_docker_container_name }}'
    --network host
    --pid host
    --restart unless-stopped
    --volume /etc/localtime:/etc/localtime:ro
    -it
    rhoriguchi/glances
