---
- name: Delete glances docker-compose dir
  file:
    path: "{{ docker_compose_glances_path }}"
    state: absent

- name: Create glances docker-compose dir
  file:
    path: "{{ docker_compose_glances_path }}"
    state: directory

- name: Copy Dockerfile to glances docker-compose dir
  copy:
    src: "{{ role_path }}/files/Dockerfile"
    dest: "{{ docker_compose_glances_path }}"
    force: yes

- name: Set glances options
  set_fact:
    glances_options: "--webserver"

- name: Generate docker-compose.yaml with correct values
  template:
    src: docker-compose.yaml.jinja2
    dest: "{{ docker_compose_glances_path }}/docker-compose.yaml"

- name: Generate glances.conf with correct values
  template:
    src: glances.conf.jinja2
    dest: "{{ docker_compose_glances_path }}/glances.conf"

- name: Start docker-compose containers
  command: docker-compose up --build --detach --force-recreate
  args:
    chdir: "{{ docker_compose_glances_path }}"
