- name: Add user glances
  user:
    name: glances
    login_class: system
    create_home: no

- stat:
    path: "{{ glances_virual_env_path }}"
  register: stat_result

- name: Create glances virtual env dir
  file:
    path: "{{ glances_virual_env_path }}"
    state: directory

- name: Create glances virtual env if not exists
  command: "python3 -m venv {{ glances_virual_env_path }}"
  when: stat_result.stat.exists == False

- name: Install pip requirements
  pip:
    name: [setuptools, glances, bottle, hddtemp, wifi, requests]
    virtualenv: "{{ glances_virual_env_path }}"

- name: Change permissions glances virtual env
  become: yes
  become_user: root
  file:
    path: "{{ glances_virual_env_path }}"
    owner: glances
    group: glances
    recurse: yes

- name: Copy glances.service to /etc/systemd/system
  copy:
    src: glances.service
    dest: /etc/systemd/system

- name: Replace ExecStart= line with correct value in glances.service
  lineinfile:
    path: /etc/systemd/system/glances.service
    regexp: "^ExecStart=$"
    line: "ExecStart={{ glances_virual_env_path }}/bin/glances -w"

- name: Restart glances.service and enable
  service:
    name: glances.service
    state: restarted
    enabled: yes
    daemon_reload: yes
