---
- name: Install apt stow
  apt:
    name:
      - stow
    state: latest
    install_recommends: no
    update_cache: yes

- name: Delete dotfiles repo
  file:
    path: "{{ user.default.dotfiles_path }}"
    state: absent

- name: Clone dotfiles repo to default user
  become: yes
  become_user: "{{ user.default.name }}"
  git:
    repo: https://github.com/rhoriguchi/dotfiles.git
    dest: "{{ user.default.dotfiles_path }}"

- name: Change permissions for init.sh for dotfiles
  file:
    path: "{{ user.default.dotfiles_path }}/init.sh"
    mode: +x
    owner: "{{ user.default.name }}"

- name: Execute init.sh for dotfiles
  become: yes
  become_user: "{{ user.default.name }}"
  command: "sh {{ user.default.dotfiles_path }}/init.sh"

- name: Create .git-credentials file
  become: yes
  become_user: "{{ user.default.name }}"
  lineinfile:
    create: yes
    path: "{{ user.default.home }}/.git-credentials"
    line: "https://{{ vault.github.username }}:{{ vault.github.password }}@github.com"
  no_log: true
