---
- name: "Install {{ user.default.shell }}"
  apt:
    name:
      - "{{ user.default.shell }}"
    state: latest
    install_recommends: no
    update_cache: yes

- name: Add group docker
  group:
    name: docker
    state: present

- name: "Add default user {{ user.default.name }}"
  user:
    name: "{{ user.default.name }}"
    password: "{{ vault.user.default.password | password_hash('sha512') }}"
    uid: "{{ user.default.id }}"
    shell: "/bin/{{ user.default.shell }}"
    groups: docker,sudo,users
    append: yes
