---
- name: Install apt stow zsh
  apt:
    name:
      - stow
      - zsh
    state: latest
    install_recommends: no
    update_cache: yes

- name: Add spi group
  group:
    name: spi
    state: present

- name: Add gpio group
  group:
    name: gpio
    state: present

- name: Add i2c group
  group:
    name: i2c
    state: present

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add default user
  user:
    name: "{{ default_user }}"
    password: "{{ default_user_password }}"
    uid: 4242
    shell: /usr/bin/zsh
    groups: adm,dialout,cdrom,sudo,audio,plugdev,games,users,input,netdev,spi,i2c,gpio,docker
    append: yes
