# TODO use default way to install docker

- name: Pip install docker
  pip:
    name: docker

- name: Create docker lib dir
  file:
    path: "{{ default_docker_lib_path }}"
    state: directory

- name: Create docker lib symbolic link dir
  file:
    path: "{{ docker_data_path }}"
    state: directory

- name: Create symbolic link from docker lib dir to external drive
  file:
    src: "{{ default_docker_lib_path }}"
    dest: "{{ docker_data_path }}"
    state: link
    force: yes

- name: Download get-docker.sh from get.docker.com
  become: yes
  become_user: root
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: +x

- name: Run get-docker.sh
  become: yes
  become_user: root
  shell: /tmp/get-docker.sh

- name: Start docker engine
  become: yes
  become_user: root
  shell: docker engine start

- name: Add docker group
  group:
    name: docker
    state: present
