- name: Pip install docker
  pip:
    name: docker

- name: Create docker lib dir
  file:
    path: "{{ default_docker_lib_path }}"
    state: directory

- name: Create docker lib symbolic link dir
  file:
    path: "{{ docker_data_path }}"
    state: directory

- name: Create symbolic link from docker lib dir to external drive
  file:
    src: "{{ default_docker_lib_path }}"
    dest: "{{ docker_data_path }}"
    state: link
    force: yes

- name: Download get-docker.sh from get.docker.com
  become: yes
  become_user: root
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: +x

- name: Run get-docker.sh
  become: yes
  become_user: root
  shell: /tmp/get-docker.sh

# TODO commented
#
# - name: Add docker apt key
#   apt_key:
#     url: "https://download.docker.com/linux/{{ os }}/gpg"
#     state: present
#
# - name: Add docker apt repository
#   apt_repository:
#     filename: docker
#     repo: "deb [arch={{ architecture }}] https://download.docker.com/linux/{{ os }} bionic stable"
#     state: present
#     update_cache: yes
#
# - name: Install apt ['docker-ce', 'docker-ce-cli', 'containerd.io']
#   apt:
#     name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
#     state: latest

- name: Add docker group
  group:
    name: docker
    state: present
