- name: Delete dotfiles repo if exist
  file:
    path: "{{ default_user_dotfiles_path }}"
    state: absent

- name: Clone dotfiles repo to default user
  become: yes
  become_user: "{{ default_user }}"
  git:
    repo: https://github.com/rhoriguchi/dotfiles.git
    dest: "{{ default_user_dotfiles_path }}"

- name: Change permissions for init.sh for dotfiles
  become: yes
  become_user: root
  file:
    path: "{{ default_user_dotfiles_path }}/init.sh"
    mode: +x
    owner: "{{ default_user }}"

- name: Execute init.sh for dotfiles
  become: yes
  become_user: "{{ default_user }}"
  command: "sh {{ default_user_dotfiles_path }}/init.sh"

- name: Create .git-credentials file
  become: yes
  become_user: "{{ default_user }}"
  lineinfile:
    create: yes
    path: "{{ default_user_home }}/.git-credentials"
    line: "https://{{ git_user }}:{{ git_password }}@github.com"

- name: Ensure that locale en_US.UTF-8 exists
  locale_gen:
    name: en_US.UTF-8
    state: present
