- name: Change hostname in /etc/hostname
  copy:
    content: "{{ hostname }}"
    dest: /etc/hostname

- name: Change hostname in /etc/hosts
  copy:
    content: "{{ hostname }}"
    dest: /etc/hosts

- name: Restart networking
  service:
    name: networking
    state: restarted
