---
- name: Change hostname in /etc/hostname
  copy:
    content: "{{ hostname }}"
    dest: /etc/hostname

- name: Change hostname in /etc/hosts
  copy:
    content: |
      127.0.0.1     localhost
      127.0.1.1     {{ hostname }}
    dest: /etc/hosts

- name: Restart networking service
  service:
    name: networking
    state: restarted
  ignore_errors: yes
