---
- name: "Set hostname as {{ system_hostname }}"
  hostname:
    name: "{{ system_hostname }}"

- name: Change hostname in /etc/hosts
  copy:
    content: |
      127.0.0.1     localhost
      127.0.1.1     {{ system_hostname }}
    dest: /etc/hosts

- import_tasks: "{{ playbook_dir }}/helper/reboot.yaml"
