- name: Install apt requirements
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  with_items:
    - net-tools
    - nmap
    - libssl-dev
    - openssl

- name: Add user homeassistant
  user:
    name: homeassistant
    login_class: system

- name: Check if homeassistant virtual env dir exists
  stat:
    path: "{{ homeassistant_virual_env_path }}"
  register: stat_result

- name: Create homeassistant virtual env dir
  file:
    path: "{{ homeassistant_virual_env_path }}"
    state: directory

- name: Create homeassistant virtual env
  command: "python3 -m venv {{ homeassistant_virual_env_path }}"
  when: stat_result.stat.exists == False

- name: Clone homeassistant to tmp
  git:
    repo: "{{ homeassistant_repo_url }}"
    dest: "{{ homeassistant_tmp_repo_path }}"

- name: Include vars of homeassistant config.yaml into homeassistant variable
  include_vars:
    file: "{{ homeassistant_tmp_repo_path }}/config.yaml"
    name: homeassistant

- name: Delete homeassistant repo
  file:
    path: "{{ homeassistant_tmp_repo_path }}"
    state: absent

- name: Pip install homeassistant
  pip:
    name: homeassistant
    version: "{{ homeassistant.version }}"
    virtualenv: "{{ homeassistant_virual_env_path }}"
  when: stat_result.stat.exists == False

- name: Change permissions homeassistant virtual env
  become: yes
  become_user: root
  file:
    path: "{{ homeassistant_virual_env_path }}"
    owner: homeassistant
    group: homeassistant
    recurse: yes

- name: Copy home-assistant@homeassistant.service to /etc/systemd/system
  copy:
    src: homeassistant/home-assistant@homeassistant.service
    dest: /etc/systemd/system

- name: Replace ExecStart= line with correct value in home-assistant@homeassistant.service
  lineinfile:
    path: /etc/systemd/system/home-assistant@homeassistant.service
    regexp: "^ExecStart=$"
    line: "ExecStart={{ homeassistant_virual_env_path }}/bin/hass -c '{{ dot_homeassistant_path }}'"
