- name: Install autossh
  apt:
    name: autossh
    state: latest
    install_recommends: no

- name: Add ssh key to user homeassistant
  user:
    name: homeassistant
    login_class: system
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: "homeassistant@{{ hostname }}"

- name: Change owner of .ssh in homeassistant home
  file:
    path: "{{ homeassistant_home_path }}/.ssh"
    state: directory
    owner: homeassistant
    group: homeassistant

- name: Copy config in to .ssh in homeassistant home
  copy:
    src: ssh_tunnel/config
    dest: "{{ homeassistant_home_path }}/.ssh"
    owner: homeassistant
    group: homeassistant
    mode: 0x700

- name: Copy xxlpitu-jcrk-tunnel.service to /etc/systemd/system/
  copy:
    src: ssh_tunnel/xxlpitu-jcrk-tunnel.service
    dest: /etc/systemd/system

- name: Add line with enviroment variable AUTOSSH_LOGFILE to xxlpitu-jcrk-tunnel.service
  lineinfile:
    path: /etc/systemd/system/xxlpitu-jcrk-tunnel.service
    insertafter: ^Environment="AUTOSSH_GATETIME=0"$
    line: "AUTOSSH_LOGFILE={{ homeassistant_home_path }}/autossh.log"

- name: Restart xxlpitu-jcrk-tunnel.service and enable
  service:
    name: xxlpitu-jcrk-tunnel.service
    state: restarted
    enabled: yes
    daemon_reload: yes
