---
- include: plex/main.yaml
- include: tautulli.yaml

- name: Delete plex docker-compose dir
  file:
    path: "{{ data_path.library.docker_compose.plex }}"
    state: absent

- name: Create plex docker-compose dir
  file:
    path: "{{ data_path.library.docker_compose.plex }}"
    state: directory

- name: Generate docker-compose.yaml with correct values
  template:
    src: docker-compose.yaml.jinja2
    dest: "{{ data_path.library.docker_compose.plex }}/docker-compose.yaml"

- name: Run docker-compose pull
  command: docker-compose pull
  args:
    chdir: "{{ data_path.library.docker_compose.plex }}"

- name: Run docker-compose up
  command: docker-compose up --build --detach --remove-orphans
  args:
    chdir: "{{ data_path.library.docker_compose.plex }}"
