- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    install_recommends: no

- name: Add apt plexmediaserver trusted key
  apt_key:
    url: https://dev2day.de/pms/dev2day-pms.gpg.key
    state: present

- name: Add apt plexmediaserver repository
  apt_repository:
    repo: deb https://dev2day.de/pms/ jessie main
    state: present
    filename: pms

- name: Run the equivalent of apt-get update
  apt:
    update_cache: yes

- name: Install plexmediaserver
  apt:
    name: plexmediaserver
    default_release: jessie
    state: latest
    install_recommends: no

- name: Create plex-data dir
  file:
    path: "{{ plex_data_path }}"
    state: directory
    owner: plex
    group: plex

- name: Check if Plex Media Server data exists
  stat:
    path: "{{ default_plex_data_path }}"
  register: stat_result

- name: Copy Plex Media Server data
  copy:
    src: "{{ default_plex_data_path }}"
    dest: "{{ plex_data_path }}"
    state: directory
    owner: plex
    group: plex
  when: stat_result.stat.exists == True and stat_result.stat.islnk == False

- name: Delete Plex Media Server data
  file:
    path: "{{ default_plex_data_path }}"
    state: absent
  when: stat_result.stat.exists == True and stat_result.stat.islnk == False

- name: Create symbolic link from Plex Media Server to copy
  file:
    src: "{{ plex_data_path }}/Plex Media Server"
    dest: "{{ default_plex_data_path }}"
    state: link
    force: yes
    owner: plex
    group: plex

- name: Add plex user to rslsync group
  user:
    name: plex
    group: rslsync
    append: yes

- name: Restart plexmediaserver and enable
  service:
    name: plexmediaserver.service
    state: restarted
    enabled: yes
