---
- name: Build plex image
  docker_image:
    name: linuxserver/plex

- name: Create plex data dir
  file:
    path: "{{ plex_data_path }}"
    state: directory

- name: Delete plex container
  shell: docker rm --force plex
  ignore_errors: yes

- name: Create plex container
  shell: >-
    docker run
    --detach
    --env HOSTNAME='{{ hostname }}'
    --env TZ='{{ timezone }}'
    --env VERSION=public
    --mount src='{{ plex_data_path }}',target='/config/Library/Application Support/Plex Media Server',type=bind
    --mount src='{{ resilio_sync_save_path }}',target=/data/sync,type=bind
    --name plex
    --network host
    --restart unless-stopped
    linuxserver/plex
