---
- name: Delete homeassistant tmp repo
  file:
    path: "{{ homeassistant_tmp_repo_path }}"
    state: absent

- name: Clone homeassistant to tmp
  git:
    repo: https://github.com/rhoriguchi/homeassistant.git
    dest: "{{ homeassistant_tmp_repo_path }}"

- include_vars:
    file: "{{ homeassistant_tmp_repo_path }}/config.yaml"
    name: homeassistant

- name: Use raspberrypi3 homeassistant image
  set_fact:
    homeassistant_docker_image: "homeassistant/raspberrypi3-homeassistant"
  when: ansible_lsb.id == "Raspbian"

- name: Use default homeassistant image
  set_fact:
    homeassistant_docker_image: "homeassistant/home-assistant-homeassistant"
  when: ansible_lsb.id != "Raspbian"

- name: Build home-assistant image
  docker_image:
    name: "{{ homeassistant_docker_image }}:{{ homeassistant.version }}"

- name: Create homeassistant data dir
  file:
    path: "{{ homeassistant_data_path }}"
    state: directory

- name: Synchronize .homeassistant to homeassistant config dir
  synchronize:
    src: "{{ homeassistant_tmp_repo_path }}/.homeassistant"
    dest: "{{ homeassistant_data_path }}"
    delete: no
    recursive: yes

- name: Delete homeassistant_secrets tmp repo
  file:
    path: "{{ homeassistant_secrets_tmp_repo_path }}"
    state: absent

- name: Clone homeassistant_secrets to tmp
  git:
    repo: "https://{{ git_user }}:{{ git_password }}@github.com/rhoriguchi/homeassistant_secrets.git"
    dest: "{{ homeassistant_secrets_tmp_repo_path }}"

- include_vars:
    file: "{{ homeassistant_secrets_tmp_repo_path }}/secrets.yaml"

- name: Copy secrets.yaml to homeassistant config dir
  copy:
    src: "{{ homeassistant_secrets_tmp_repo_path }}/secrets.yaml"
    dest: "{{ dot_homeassistant_path }}"
    force: yes

- name: Delete homeassistant_secrets temp repo
  file:
    path: "{{ homeassistant_secrets_tmp_repo_path }}"
    state: absent

- name: Generate phue.conf with correct hue token in homeassistant config dir
  template:
    src: homeassistant/phue.conf
    dest: "{{ dot_homeassistant_path }}"

- name: Delete home-assistant.log
  file:
    path: "{{ dot_homeassistant_path }}/home-assistant.log"
    state: absent

- name: Delete homeassistant container
  shell: docker rm --force homeassistant
  ignore_errors: yes

- name: Create homeassistant container
  shell: >-
    docker run
    --detach
    --mount src='{{ dot_homeassistant_path }}',target=/config,type=bind
    --mount src='{{ letsencrypt_data_path }}',target=/le-ssl,type=bind
    --name homeassistant
    --network host
    --restart unless-stopped
    --volume /etc/localtime:/etc/localtime:ro
    {{ homeassistant_docker_image }}:{{ homeassistant.version }}
