---
- name: Delete homeassistant tmp repo
  file:
    path: "{{ homeassistant_tmp_repo_path }}"
    state: absent

- name: Clone homeassistant to tmp
  git:
    repo: https://github.com/rhoriguchi/homeassistant.git
    dest: "{{ homeassistant_tmp_repo_path }}"

- name: Create fetch dir
  file:
    path: "{{ tmp_fetch_dir }}"
    state: directory

- name: Fetch config.yaml from remote host
  fetch:
    src: "{{ homeassistant_tmp_repo_path }}/config.yaml"
    dest: "{{ tmp_fetch_dir }}/config.yaml"
    flat: yes

- include_vars:
    file: "{{ tmp_fetch_dir }}/config.yaml"
    name: homeassistant

- name: Delete fetch dir
  file:
    path: "{{ tmp_fetch_dir }}"
    state: absent

- name: Use raspberrypi3 homeassistant image
  set_fact:
    homeassistant_docker_image: "homeassistant/raspberrypi3-homeassistant"
  when: ansible_lsb.id == "Raspbian"

- name: Use default homeassistant image
  set_fact:
    homeassistant_docker_image: "homeassistant/{{ ansible_architecture }}-homeassistant"
  when: ansible_lsb.id != "Raspbian"

- name: Create homeassistant data dir
  file:
    path: "{{ homeassistant_data_path }}"
    state: directory

- name: Synchronize .homeassistant to homeassistant config dir
  synchronize:
    src: "{{ homeassistant_tmp_repo_path }}/.homeassistant"
    dest: "{{ homeassistant_data_path }}"
    delete: no
    recursive: yes
  delegate_to: "{{ inventory_hostname }}"

- name: Delete homeassistant_secrets tmp repo
  file:
    path: "{{ homeassistant_secrets_tmp_repo_path }}"
    state: absent

- name: Clone homeassistant_secrets to tmp
  git:
    repo: "https://{{ vault_git_user }}:{{ vault_git_password }}@github.com/rhoriguchi/homeassistant_secrets.git"
    dest: "{{ homeassistant_secrets_tmp_repo_path }}"
  no_log: true

- name: Create fetch dir
  file:
    path: "{{ tmp_fetch_dir }}"
    state: directory

- name: Fetch secrets.yaml from remote host
  fetch:
    src: "{{ homeassistant_secrets_tmp_repo_path }}/secrets.yaml"
    dest: "{{ tmp_fetch_dir }}/secrets.yaml"
    flat: yes

- include_vars:
    file: "{{ tmp_fetch_dir }}/secrets.yaml"

- name: Delete fetch dir
  file:
   path: "{{ tmp_fetch_dir }}"
   state: absent

# TODO use copy module
- name: Copy secrets.yaml to homeassistant config dir
  command: "cp '{{ homeassistant_secrets_tmp_repo_path }}/secrets.yaml' '{{ dot_homeassistant_path }}'"

- name: Delete homeassistant_secrets temp repo
  file:
    path: "{{ homeassistant_secrets_tmp_repo_path }}"
    state: absent

- name: Generate phue.conf with correct hue token in homeassistant config dir
  template:
    src: homeassistant/phue.conf.jinja2
    dest: "{{ dot_homeassistant_path }}/phue.conf"

- name: Replace base_url in homeassistant configuration.yaml
  replace:
    path: "{{ dot_homeassistant_path }}/configuration.yaml"
    regexp: "base_url:\\s.*$"
    replace: "base_url: https://{{ url }}"

- name: Replace http://localhost with http://glances in homeassistant sensor/glances_localhost.yaml
  replace:
    path: "{{ dot_homeassistant_path }}/sensor/glances_localhost.yaml"
    regexp: "http:\\/\\/localhost"
    replace: "http://glances"

- name: Delete home-assistant.log
  file:
    path: "{{ dot_homeassistant_path }}/home-assistant.log"
    state: absent
