---
- name: Create letsencrypt dir
  file:
    path: "{{ data_path.library.letsencrypt }}"
    state: directory

- name: Create nginx dir
  file:
    path: "{{ data_path.library.nginx }}"
    state: directory

- name: Generate nginx/app.conf with correct values
  template:
    src: letsencrypt/nginx/default.jinja2
    dest: "{{ data_path.library.nginx }}/default"
