---
- name: Create homeassistant letsencrypt dir
  file:
    path: "{{ letsencrypt_homeassistant_path }}"
    state: directory

- name: Create homeassistant nginx dir
  file:
    path: "{{ nginx_homeassistant_path }}"
    state: directory

- name: Generate nginx/app.conf with correct values
  template:
    src: letsencrypt/nginx/default.jinja2
    dest: "{{ nginx_homeassistant_path }}/default"
