- name: Add apt resilio-sync trusted key
  apt_key:
    state: present
    url: https://linux-packages.resilio.com/resilio-sync/key.asc

- name: Add apt resilio-sync repository
  apt_repository:
    repo: deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free
    state: present
    filename: resilio-sync

- name: Run the equivalent of apt-get update
  apt:
    update_cache: yes

- name: Install resilio-sync
  apt:
    name: resilio-sync
    state: latest
    install_recommends: no

- name: Add user rslsync to group rslsync
  user:
    name: rslsync
    group: rslsync
    append: yes

- name: Create resilio-sync Sync dir
  file:
    path: "{{ main_drive_path }}/Sync"
    state: directory
    owner: rslsync
    group: rslsync
    mode: 0755

- name: Create resilio-sync SyncDownloads dir
  file:
    path: "{{ main_drive_path }}/SyncDownloads"
    state: directory
    owner: rslsync
    group: rslsync
    mode: 0755

- name: Restart resilio-sync and enable
  service:
    name: resilio-sync.service
    state: restarted
    enabled: yes
    daemon_reload: yes
