# TODO sub task of homeassistant_init

- name: Install autossh
  apt:
    name: autossh
    state: latest
    install_recommends: no

- name: Create .ssh in homeassistant home
  file:
    path: "{{ homeassistant_home_path }}/.ssh"
    state: directory
    owner: homeassistant
    group: homeassistant

- name: Copy config in to .ssh in homeassistant home
  copy:
    src: config
    dest: "{{ homeassistant_home_path }}/.ssh"
    owner: homeassistant
    group: homeassistant
    mode: 0x600

- name: Copy xxlpitu-jcrk-tunnel.service to /etc/systemd/system/
  copy:
    src: xxlpitu-jcrk-tunnel.service
    dest: /etc/systemd/system

- name: Add environment variable AUTOSSH_LOGFILE to .bashrc
  blockinfile:
    path: "{{ homeassistant_home_path }}/.bashrc"
    content: AUTOSSH_LOGFILE="$HOME/autossh.log"

- name: Restart xxlpitu-jcrk-tunnel.service and enable
  service:
    name: xxlpitu-jcrk-tunnel.service
    state: restarted
    enabled: yes
    daemon_reload: yes
