---
- name: Add apt key for docker
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg"
    state: present

- name: Get hardware architecture
  command: dpkg --print-architecture
  register: hardware_architecture

- name: Set hardware architecture
  set_fact:
    hardware_architecture: "{{ hardware_architecture.stdout }}"

- name: Add apt repository for docker
  apt_repository:
    filename: docker
    repo: "deb [arch={{ hardware_architecture }}] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename | lower }} stable"
    state: present
    update_cache: yes

- name: Purge apt docker docker-engine docker.io lxc-docker
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - lxc-docker
    state: absent
    purge: yes
    update_cache: yes

- name: Install apt apt-transport-https ca-certificates curl software-properties-common
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install apt containerd.io docker-ce docker-ce-cli
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: latest
    install_recommends: no
    update_cache: yes

