---
- name: Pip install docker
  pip:
    name: docker

- name: Add apt key for docker
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg"
    state: present

# TODO can probably be found out with ansible variable
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html
- name: Get hardware architecture
  command: dpkg --print-architecture
  register: hardware_architecture

- name: Add apt repository for docker
  apt_repository:
    filename: docker
    repo: "deb [arch={{ hardware_architecture.stdout }}] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename | lower }} stable"
    state: present
    update_cache: yes

- name: Purge docker docker-engine docker.io lxc-docker
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - lxc-docker
    state: absent
    purge: yes
    update_cache: yes

- name: Install apt-transport-https ca-certificates curl software-properties-common
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest
    install_recommends: no
    update_cache: yes

- import_tasks: "{{ playbook_dir }}/helper/reboot.yaml"

- name: Install containerd.io docker-ce docker-ce-cli
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: latest
    install_recommends: no
    update_cache: yes
