---
- name: Install apt libffi-dev libssl-dev python3 python3-dev python3-pip
  apt:
    name:
      - libffi-dev
      - libssl-dev
      - python3
      - python3-dev
      - python3-pip
    state: latest
    install_recommends: no
    update_cache: yes

- name: Update pip3
  pip:
    name: pip
    executable: pip3
    state: latest

- name: Pip install docker-compose
  pip:
    name: docker-compose

- name: Change permissions for docker-compose +x
  shell: sudo chmod +x /usr/local/bin/docker-compose
