---
- name: Install libffi-dev libssl-dev python3-dev
  apt:
    name:
      - libffi-dev
      - libssl-dev
      - python3-dev
    state: latest
    install_recommends: no
    update_cache: yes

- name: Pip install docker-compose
  pip:
    name: docker-compose
