---
- name: Build duckdns image
  docker_image:
    name: linuxserver/duckdns

- name: Delete duckdns container
  shell: docker rm --force duckdns
  ignore_errors: yes

- name: Create duckdns container
  shell: >-
    docker run
    --detach
    --env SUBDOMAINS='{{ duckdns_domain }}'
    --env TOKEN='{{ duckdns_token }}'
    --env TZ='{{ timezone }}'
    --name duckdns
    --restart unless-stopped
    linuxserver/duckdns
