---
- name: Create duckdns data dir
  file:
    path: "{{ duckdns_data_path }}"
    state: directory

- name: Create duckdns /duck.log file
  file:
    path: "{{ duckdns_data_path }}/duck.log"
    state: touch

- name: Delete duckdns docker-compose dir
  file:
    path: "{{ docker_compose_duckdns_path }}"
    state: absent

- name: Create duckdns docker-compose dir
  file:
    path: "{{ docker_compose_duckdns_path }}"
    state: directory

- name: Copy Dockerfile to duckdns docker-compose dir
  copy:
    src: "{{ role_path }}/files/Dockerfile"
    dest: "{{ docker_compose_duckdns_path }}"
    force: yes

- name: Generate docker-compose.yaml with correct values
  template:
    src: docker-compose.yaml.jinja2
    dest: "{{ docker_compose_duckdns_path }}/docker-compose.yaml"

- name: Start docker-compose containers
  shell: docker-compose up --build --detach --force-recreate
  args:
    chdir: "{{ docker_compose_duckdns_path }}"
