---
- name: Generate config.yaml with correct values
  template:
    src: config.yaml
    dest: "{{ role_path }}/files/config.yaml"

- name: Build tv_time_export image
  docker_image:
    name: "rhoriguchi/tv_time_export/{{ tv_time_username | replace('@', '_at_') }}"
    path: "{{ role_path }}/files"

- name: Delete config.yaml
  file:
    path: config.yaml
    state: absent

- name: Create tv_time_export exports dir
  file:
    path: "{{ tv_time_export_path }}t"
    state: directory

- name: Create tv_time_export data dir
  file:
    path: "{{ tv_time_export_data_path }}"
    state: directory

- name: Create tv_time_export log file
  file:
    path: "{{ tv_time_export_data_path }}/tv_time_export.log"
    state: touch

- name: Delete tv_time_export container
  shell: "docker rm --force tv_time_export_{{ tv_time_username | replace('@', '_at_') }}"
  ignore_errors: yes

- name: Create tv_time_export container
  shell: >-
    docker run
    --detach
    --env TZ='{{ timezone }}'
    --mount src='{{ tv_time_export_path }}t',target=/tv_time_export/exports,type=bind
    --mount src='{{ tv_time_export_data_path }}/tv_time_export.log',target=/tv_time_export/src/tv_time_export.log,type=bind
    --name 'tv_time_export_{{ tv_time_username | replace('@', '_at_') }}'
    --restart unless-stopped
    rhoriguchi/tv_time_export/{{ tv_time_username | replace('@', '_at_') }}
