- name: Delete tv_time_export repo if exist
  file:
    path: "{{ default_user_tv_time_export_path }}"
    state: absent

- name: Clone tv_time_export repo to default user
  become: yes
  become_user: "{{ default_user }}"
  git:
    repo: https://github.com/rhoriguchi/tv_time_export.git
    dest: "{{ default_user_tv_time_export_path }}"

- name: Create tv_time_export Resilio Sync dir
  file:
    path: "{{ tv_time_export_save_path }}"
    state: directory
    owner: rslsync
    group: rslsync
    mode: 0755

- name: Create config.yaml in tv_time_export repo and add correct values
  become: yes
  become_user: "{{ default_user }}"
  blockinfile:
    path: "{{ default_user_tv_time_export_path }}/src/config.yaml"
    create: yes
    content: |
      username: {{ tv_time_user }}
      password: {{ tv_time_password }}
      save_path: {{ tv_time_export_save_path }}

- name: Check if tv_time_export virtual env dir exists
  stat:
    path: "{{ tv_time_export_virual_env_path }}"
  register: stat_result

- name: Create tv_time_export virtual env dir
  file:
    path: "{{ tv_time_export_virual_env_path }}"
    state: directory
    when: stat_result.stat.exists == False

- name: Create tv_time_export virtual env
  command: "python3 -m venv {{ tv_time_export_virual_env_path }}"
  when: stat_result.stat.exists == False

- name: Pip install tv_time_export requirements.txt
  pip:
    requirements: "{{ default_user_tv_time_export_path }}/requirements.txt"
    virtualenv: "{{ tv_time_export_virual_env_path }}"

- name: Create tv_time_export.sh script to run tv_time_export.py
  blockinfile:
    path: "{{ default_user_tv_time_export_path }}/tv_time_export.sh"
    create: yes
    mode: +x
    content: |
      {{ tv_time_export_virual_env_path }}/bin/python {{ default_user_tv_time_export_path }}/src/tv_time_export.py >/dev/null 2>&1
      sudo chown -R rslsync:rslsync {{ tv_time_export_save_path }}

- name: Crown job for tv_time_export
  become: yes
  become_user: root
  cron:
    hour: 4
    job: "{{ default_user_tv_time_export_path }}/tv_time_export.sh >/dev/null 2>&1"
