---
- name: Create tv_time_export exports dir
  file:
    path: "{{ tv_time_export_path }}"
    state: directory

- name: Create tv_time_export data dir
  file:
    path: "{{ tv_time_export_data_path }}"
    state: directory
    
- name: Create tv_time_export /tv_time_export.log file
  file:
    path: "{{ tv_time_export_data_path }}/tv_time_export.log"
    state: touch

- name: Delete tv_time_export docker-compose dir
  file:
    path: "{{ docker_compose_tv_time_export_path }}"
    state: absent

- name: Create tv_time_export docker-compose dir
  file:
    path: "{{ docker_compose_tv_time_export_path }}"
    state: directory

- name: Copy Dockerfile to tv_time_export docker-compose dir
  copy:
    src: "{{ role_path }}/files/Dockerfile"
    dest: "{{ docker_compose_tv_time_export_path }}"
    force: yes

- name: Generate docker-compose.yaml with correct values
  template:
    src: docker-compose.yaml.jinja2
    dest: "{{ docker_compose_tv_time_export_path }}/docker-compose.yaml"

- name: Generate myanimelist-export.yaml with correct values
  template:
    src: config.yaml.jinja2
    dest: "{{ docker_compose_tv_time_export_path }}/config.yaml"

- name: Start docker-compose containers
  shell: docker-compose up --build --detach --force-recreate
  args:
    chdir: "{{ docker_compose_tv_time_export_path }}"
