- name: Generate config.yaml with correct values
  template:
    src: config.yaml
    dest: "{{ role_path }}/files/config.yaml"

- name: Build tv_time_export image
  docker_image:
    name: "rhoriguchi/tv_time_export/{{ tv_time_user | replace('@', '_at_') }}"
    path: "{{ role_path }}/files"

- name: Delete config.yaml
  file:
    path: config.yaml
    state: absent

- name: Create tv_time_export exports dir
  file:
    path: "{{ resilio_sync_save_path }}/tv_time_export"
    state: directory

- name: Delete tv_time_export container
  shell: "docker rm --force tv_time_export_{{ tv_time_user | replace('@', '_at_') }}"
  ignore_errors: yes

- name: Create tv_time_export container
  shell: >-
    docker run
    --detach
    --mount src='{{ resilio_sync_save_path }}/tv_time_export',target=/tv_time_export/exports,type=bind
    --name 'tv_time_export_{{ tv_time_user | replace('@', '_at_') }}'
    --restart unless-stopped
    rhoriguchi/tv_time_export/{{ tv_time_user | replace('@', '_at_') }}
