- name: Delete tv_time_export repo if exist
  file:
    path: "{{ default_user_tv_time_export_path }}"
    state: absent

- name: Clone tv_time_export repo to default user
  become: yes
  become_user: "{{ default_user }}"
  git:
    repo: https://github.com/rhoriguchi/tv_time_export.git
    dest: "{{ default_user_tv_time_export_path }}"

- name: Create tv_time_export Resilio Sync dir
  file:
    path: "{{ tv_time_export_save_path }}"
    state: directory
    owner: rslsync
    group: rslsync
    mode: 0755

- name: Create config.yaml in tv_time_export repo and add correct values
  become: yes
  become_user: "{{ default_user }}"
  blockinfile:
    path: "{{ default_user_tv_time_export_path }}/config.yaml"
    create: yes
    content: |
      "username: {{ tv_time_export_user }}"
      "password: {{ tv_time_export_password }}"
      "save_path: {{ tv_time_export_save_path }}"

- name: Check if tv_time_export virtual env dir exists
  stat:
    path: "{{ tv_time_export_virual_env_path }}"
  register: stat_result

- name: Create tv_time_export virtual env dir
  file:
    path: "{{ tv_time_export_virual_env_path }}"
    state: directory

- name: Create tv_time_export virtual env
  command: "python3 -m venv {{ tv_time_export_virual_env_path }}"
  when: stat_result.stat.exists == False

- name: Pip install tv_time_export requirements.txt
  pip:
    requirements: "{{ default_user_tv_time_export_path }}/requirements.txt"
    virtualenv: "{{ tv_time_export_virual_env_path }}"

- name: Crown job for tv_time_export
  become: yes
  become_user: root
  cron:
    hour: 4
    job: "source {{ tv_time_export_virual_env_path }}/bin/activate && {{ default_user_tv_time_export_path }}/main.py >/dev/null 2>&1"

- name: Restart cron service
  become: yes
  become_user: root
  service:
    name: cron
    state: restarted
