---
- name: Delete Absolute-Series-Scanner temp dir if exist
  file:
    path: "{{ absolute_series_scanner_tmp_path }}"
    state: absent

- name: Clone Absolute-Series-Scanner to temp dir
  git:
    repo: https://github.com/ZeroQI/Absolute-Series-Scanner.git
    dest: "{{ absolute_series_scanner_tmp_path }}"

- name: Create Scanners dir in plex dir if not exists
  file:
    path: "{{ plex_data_path }}/Scanners"
    state: directory

- name: Create Scanners/Series dir in plex dir if not exists
  file:
    path: "{{ plex_data_path }}/Scanners/Series"
    state: directory

- name: Copy "Absolute Series Scanner.py" to plex Scanners/Series path
  copy:
    src: "{{ absolute_series_scanner_tmp_path }}/Scanners/Series/Absolute Series Scanner.py"
    dest: "{{ plex_data_path }}/Scanners/Series"
