- name: Delete Absolute-Series-Scanner temp folder if exist
  file:
    path: "{{ absolute_series_scanner_tmp_path }}"
    state: absent

- name: Clone Absolute-Series-Scanner to temp folder
  git:
    repo: https://github.com/ZeroQI/Absolute-Series-Scanner.git
    dest: "{{ absolute_series_scanner_tmp_path }}"

- name: Create Scanners folder in plex dir if not exists
  file:
    path: "{{ plex_data_path }}/Plex Media Server/Scanners"
    state: directory

- name: Create Scanners/Series folder in plex dir if not exists
  file:
    path: "{{ plex_data_path }}/Plex Media Server/Scanners/Series"
    state: directory

- name: Copy "Absolute Series Scanner.py" to plex Scanners/Series path
  copy:
    src: "{{ absolute_series_scanner_tmp_path }}/Scanners/Series/Absolute Series Scanner.py"
    dest: "{{ plex_data_path }}/Plex Media Server/Scanners/Series"
