homeassistant_data_path: "{{ main_drive_path }}/library/homeassistant"
letsencrypt_data_path: "{{ main_drive_path }}/library/letsencrypt"
plex_data_path: "{{ main_drive_path }}/library/plex"
resilio_sync_data_path: "{{ main_drive_path }}/library/resilio-sync"
tautulli_data_path: "{{ main_drive_path }}/library/tautulli"
tv_time_export_data_path: "{{ main_drive_path }}/library/tv_time_export"
