---
- name: Add group docker
  group:
    name: docker
    state: present

- name: Add user ansible
  user:
    name: ansible
    password: "{{ vault_ansible_user_password | password_hash('sha512') }}"
    uid: 3131
    shell: /usr/bin/bash
    groups: docker,sudo,users
    append: yes
