---
- name: "Install {{ user.default.shell }}"
  apt:
    name:
      - "{{ user.default.shell }}"
    state: latest
    install_recommends: no
    update_cache: yes

- name: Add group docker
  group:
    name: docker
    state: present

- name: Add user ansible
  user:
    name: ansible
    password: "{{ vault.user.ansible.password | password_hash('sha512') }}"
    uid: "{{ user.ansible.id }}"
    shell: "/bin/{{ user.ansible.shell }}"
    groups: docker,sudo,users
    append: yes

- name: Create empty .zshrc file
  copy:
    content: ""
    dest: /home/ansible/.zshrc
    force: no
