---
- name: Pip install docker
  pip:
    name: docker

- name: Add apt key for docker
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg"
    state: present

- name: Hardware architecture is armhf
  set_fact:
    hardware_architecture: armhf
  when: ansible_architecture == "armv7l"

- name: Hardware architecture is arm64
  set_fact:
    hardware_architecture: arm64
  when: ansible_architecture == "aarch64"

- name: Add apt repository for docker
  apt_repository:
    filename: docker
    repo: "deb [arch={{ hardware_architecture }}] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename | lower }} stable"
    state: present
    update_cache: yes

- name: Purge apt docker docker-engine docker.io lxc-docker
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - lxc-docker
    state: absent
    purge: yes
    update_cache: yes

- name: Install apt apt-transport-https ca-certificates curl software-properties-common
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install apt containerd.io docker-ce docker-ce-cli
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: latest
    install_recommends: no
    update_cache: yes

- name: Remove all unused ressources
  shell: docker system prune --all --force
