---
# TODO detect if bootini is present and only hold if it is

- name: Hold boot.ini upgrade
  shell: apt-mark hold bootini
  ignore_errors: yes

- name: Update package list
  shell: apt-get update

- name: Upgrade all packages to the latest version
  shell: apt-get upgrade --no-install-recommends --yes --assume-yes

- name: Upgrade distribution to the latest version
  shell: apt-get dist-upgrade --no-install-recommends --yes --assume-yes

- name: Remove dependencies that are no longer required
  shell: apt-get autoremove --yes --assume-yes

- name: Unhold boot.ini upgrade
  shell: apt-mark unhold bootini
  ignore_errors: yes

- name: Reboot system
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

- name: Install apt git python3 python3-pip python3-setuptools rsync
  apt:
    name:
      - git
      - python3
      - python3-pip
      - python3-setuptools
      - rsync
    state: latest
    install_recommends: no
    update_cache: yes
