---
- name: Check if bootini is installed
  shell: dpkg-query -W bootini
  ignore_errors: true
  register: bootini_installed

- name: Hold bootini upgrade
  command: apt-mark hold bootini
  when: bootini_installed.stdout != ""

- name: Update package list
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  command: apt-get upgrade --no-install-recommends --yes --assume-yes
  args:
    warn: false

- name: Upgrade distribution to the latest version
  command: apt-get dist-upgrade --no-install-recommends --yes --assume-yes
  args:
    warn: false

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Unhold bootini upgrade
  command: apt-mark unhold bootini
  when: bootini_installed.stdout != ""

- name: Install git python3 python3-pip python3-setuptools rsync
  apt:
    name:
      - git
      - python3
      - python3-pip
      - python3-setuptools
      - rsync
      - sshpass
    state: latest
    install_recommends: no
    update_cache: yes

- name: Update pip3
  pip:
    name: pip
    executable: pip3
    state: latest

- include: /helper/reboot.yaml
