---
# TODO detect if bootini is present and only hold if it is

- name: Hold boot.ini upgrade
  command: apt-mark hold bootini
  ignore_errors: yes

- name: Update package list
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  command: apt-get upgrade --no-install-recommends --yes --assume-yes
  args:
    warn: false

- name: Upgrade distribution to the latest version
  command: apt-get dist-upgrade --no-install-recommends --yes --assume-yes
  args:
    warn: false

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Unhold boot.ini upgrade
  command: apt-mark unhold bootini
  ignore_errors: yes

- name: Install apt git python3 python3-pip python3-setuptools rsync
  apt:
    name:
      - git
      - python3
      - python3-pip
      - python3-setuptools
      - rsync
    state: latest
    install_recommends: no
    update_cache: yes
