---
- name: "Set timezone as {{ system.timezone }}"
  timezone:
    name: "{{ system.timezone }}"

- name: "locale-gen {{ system.language }}"
  command: "locale-gen {{ system.language }}"

- name: "Set environment variable LC_ALL as {{ system.language }}"
  lineinfile:
    path: /etc/environment
    line: "LC_ALL={{ system.language }}"

- name: "Set environment variable LANG as {{ system.language }}"
  lineinfile:
    path: /etc/environment
    line: "LANG={{ system.language }}"

- name: "Set environment variable LANGUAGE as {{ system.language }}"
  lineinfile:
    path: /etc/environment
    line: "LANGUAGE={{ system.language }}"

- name: Set environment variable DEBCONF_FRONTEND as noninteractive
  lineinfile:
    path: /etc/environment
    line: DEBCONF_FRONTEND=noninteractive

- name: Set environment variable DEBIAN_FRONTEND as noninteractive
  lineinfile:
    path: /etc/environment
    line: DEBIAN_FRONTEND=noninteractive

- name: Setup shutdown time
  lineinfile:
    dest: "/etc/systemd/system.conf"
    regexp: "^DefaultTimeoutStopSec="
    line: "DefaultTimeoutStopSec={{ system.shutdown_timeout }}"
    state: present

# TODO set this /etc/default/console-setup
# https://superuser.com/questions/1332341/console-setup-causes-apt-get-update-to-hang/1332550#1332550
