---
- name: "Set timezone as {{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: "locale-gen {{ language }}"
  command: "locale-gen {{ language }}"

- name: "Set environment variable LC_ALL as {{ language }}"
  lineinfile:
    path: /etc/environment
    line: "LC_ALL={{ language }}"

- name: "Set environment variable LANG as {{ language }}"
  lineinfile:
    path: /etc/environment
    line: "LANG={{ language }}"

- name: "Set environment variable LANGUAGE as {{ language }}"
  lineinfile:
    path: /etc/environment
    line: "LANGUAGE={{ language }}"

- name: Set environment variable DEBCONF_FRONTEND as noninteractive
  lineinfile:
    path: /etc/environment
    line: DEBCONF_FRONTEND=noninteractive

- name: Set environment variable DEBIAN_FRONTEND as noninteractive
  lineinfile:
    path: /etc/environment
    line: DEBIAN_FRONTEND=noninteractive

- name: Setup shutdown time
  lineinfile:
    dest: "/etc/systemd/system.conf"
    regexp: "^DefaultTimeoutStopSec="
    line: "DefaultTimeoutStopSec={{ system.shutdown_timeout }}"
    state: present
  notify:
    - Reload systemd

# TODO set this /etc/default/console-setup
# https://superuser.com/questions/1332341/console-setup-causes-apt-get-update-to-hang/1332550#1332550
