- name: Add apt UniFi trusted key
  apt_key:
    state: present
    url: https://ftp-master.debian.org/keys/archive-key-6.0.asc
    keyring: /etc/apt/trusted.gpg.d/unifi-repo.gpg

- name: Add apt UniFi repository
  apt_repository:
    repo: deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti
    state: present
    filename: unifi

- name: Run the equivalent of apt-get update
  apt:
    update_cache: yes

- name: Install java 8
  apt:
    name: openjdk-8-jre-headless
    state: latest
    install_recommends: no

- name: Install haveged
  apt:
    name: haveged
    state: latest
    install_recommends: no

- name: Install UniFi controller
  apt:
    name: unifi
    state: latest
    install_recommends: no

- name: Restart unifi and enable
  service:
    name: unifi.service
    state: restarted
    enabled: yes
    daemon_reload: yes
