web_server: yes

schedules:
  - tasks: '*'
    interval:
      hours: 1

templates:
  torrent:
    transmission:
      enabled: yes
      host: localhost
      port: 9091
      ratio: 0
      username: transmission
      password: transmission
  tv:
    template: torrent

tasks:
  test task:
