- name: Stop home-assistant@homeassistant.service
  service:
    name: home-assistant@homeassistant.service
    state: stopped
    daemon_reload: yes

- name: Create .homeassistant in homeassistant home
  file:
    path: "{{ dot_homeassistant_path }}"
    state: directory

- name: Delete homeassistant temp repo
  file:
    path: "{{ homeassistant_tmp_repo_path }}"
    state: absent

- name: Clone homeassistant to tmp
  git:
    repo: "{{ homeassistant_repo_url }}"
    dest: "{{ homeassistant_tmp_repo_path }}"

- name: Synchronize .homeassistant to /home/homeassistant/.homeassistant
  synchronize:
    src: "{{ homeassistant_tmp_repo_path }}/.homeassistant"
    dest: "{{ homeassistant_home_path }}"
    delete: no
    recursive: yes

- name: Delete homeassistant repo
  file:
    path: "{{ homeassistant_tmp_repo_path }}"
    state: absent

- name: Delete homeassistant_secrets repo
  file:
    path: "{{ homeassistant_secrets_tmp_repo_path }}"
    state: absent

- name: Clone homeassistant_secrets to tmp
  git:
    repo: "https://rhoriguchi:{{ default_git_password }}@github.com/rhoriguchi/homeassistant_secrets.git"
    dest: "{{ homeassistant_secrets_tmp_repo_path }}"

- name: Copy secrets.yaml to .homeassistant
  copy:
    src: "{{ homeassistant_secrets_tmp_repo_path }}/secrets.yaml"
    dest: "{{ dot_homeassistant_path }}"
    force: yes

- name: Delete homeassistant_secrets repo
  file:
    path: "{{ homeassistant_secrets_tmp_repo_path }}"
    state: absent

- name: Include vars of secrets.yaml into secrets variable
  include_vars:
    file: "{{ dot_homeassistant_path }}/secrets.yaml"
    name: secrets

- name: Replace HUE_TOKEN with real hue token in phue.conf
  replace:
    path: "{{ dot_homeassistant_path }}/phue.conf"
    regexp: "HUE_TOKEN"
    replace: "{{ secrets.hue_token }}"

- name: Delete home-assistant.log
  file:
    path: "{{ dot_homeassistant_path }}/home-assistant.log"
    state: absent

- name: Change owner and group of .homeassistant to homeassistant
  file:
    path: "{{ dot_homeassistant_path }}"
    owner: homeassistant
    group: homeassistant
    recurse: yes

- name: Restart home-assistant@homeassistant.service and enable
  service:
    name: home-assistant@homeassistant.service
    state: restarted
    enabled: yes
    daemon_reload: yes
