---
- name: Create portainer data dir
  file:
    path: "{{ portainer_data_path }}"
    state: directory

- name: Create portainer /data dir
  file:
    path: "{{ portainer_data_path }}/data"
    state: directory

- name: Generate portainer admin password hash
  shell: "docker run --rm httpd:2.4-alpine htpasswd -nbB admin {{ vault_portainer_password }} | cut -d ':' -f 2"
  register: portainer_hashed_admin_password
  no_log: true

- name: Set admin password hash
  set_fact:
    portainer_hashed_admin_password: "{{ portainer_hashed_admin_password.stdout }}"

- name: Delete portainer docker-compose dir
  file:
    path: "{{ docker_compose_portainer_path }}"
    state: absent

- name: Create portainer docker-compose dir
  file:
    path: "{{ docker_compose_portainer_path }}"
    state: directory

- name: Generate docker-compose.yaml with correct values
  template:
    src: docker-compose.yaml.jinja2
    dest: "{{ docker_compose_portainer_path }}/docker-compose.yaml"

- name: Start docker-compose containers
  command: docker-compose up --build --detach --force-recreate
  args:
    chdir: "{{ docker_compose_portainer_path }}"
