---
- name: Create portainer data dir
  file:
    path: "{{ data_path.library.portainer }}"
    state: directory

- name: Create portainer /data dir
  file:
    path: "{{ data_path.library.portainer }}/data"
    state: directory

- name: Generate portainer admin password hash
  shell: "docker run --rm httpd:alpine htpasswd -nbB admin {{ vault.portainer.password }} | cut -d ':' -f 2"
  register: portainer_hashed_admin_password
  no_log: true

- name: Set admin password hash
  set_fact:
    portainer_hashed_admin_password: "{{ portainer_hashed_admin_password.stdout }}"

- name: Delete portainer docker-compose dir
  file:
    path: "{{ data_path.library.docker_compose.portainer }}"
    state: absent

- name: Create portainer docker-compose dir
  file:
    path: "{{ data_path.library.docker_compose.portainer }}"
    state: directory

- name: Generate docker-compose.yaml with correct values
  template:
    src: docker-compose.yaml.jinja2
    dest: "{{ data_path.library.docker_compose.portainer }}/docker-compose.yaml"

- name: docker-compose up
  command: docker-compose up --build --detach --remove-orphans
  args:
    chdir: "{{ data_path.library.docker_compose.portainer }}"
