- name: Stop home-assistant@homeassistant.service
  service:
    name: home-assistant@homeassistant.service
    state: stopped
    daemon_reload: yes

- stat:
    path: "{{ dot_homeassistant_path }}"
  register: stat_result

- name: Create .homeassistant in homeassistant home if no dir or no symbolic link exists
  file:
    path: "{{ dot_homeassistant_path }}"
    state: directory
  when: stat_result.stat.exists == False and stat_result.stat.islnk == False

- name: Delete homeassistant temp repo
  file:
    path: "{{ homeassistant_tmp_repo_path }}"
    state: absent

- name: Clone homeassistant to tmp
  git:
    repo: "{{ homeassistant_repo_url }}"
    dest: "{{ homeassistant_tmp_repo_path }}"

- name: Include vars of homeassistant config.yaml into homeassistant variable
  include_vars:
    file: "{{ homeassistant_tmp_repo_path }}/config.yaml"
    name: homeassistant

- name: Pip install config homeassistant version
  pip:
    name: homeassistant
    version: "{{ homeassistant.version }}"
    virtualenv: "{{ homeassistant_virual_env_path }}"

- name: Change permissions homeassistant virtual env
  become: yes
  become_user: root
  file:
    path: "{{ homeassistant_virual_env_path }}"
    owner: homeassistant
    group: homeassistant
    recurse: yes

- name: Synchronize .homeassistant to /home/homeassistant/.homeassistant
  synchronize:
    src: "{{ homeassistant_tmp_repo_path }}/.homeassistant"
    dest: "{{ homeassistant_home_path }}"
    delete: no
    recursive: yes
  when: stat_result.stat.islnk == False

- name: Synchronize .homeassistant to homeassistant symbolic link location
  synchronize:
    src: "{{ homeassistant_tmp_repo_path }}"
    dest: "{{ stat_result.stat.lnk_source }}"
    delete: no
    recursive: yes
  when: stat_result.stat.islnk == True

- name: Delete homeassistant repo
  file:
    path: "{{ homeassistant_tmp_repo_path }}"
    state: absent

- name: Delete homeassistant_secrets repo
  file:
    path: "{{ homeassistant_secrets_tmp_repo_path }}"
    state: absent

- name: Clone homeassistant_secrets to tmp
  git:
    repo: "https://rhoriguchi:{{ default_git_password }}@github.com/rhoriguchi/homeassistant_secrets.git"
    dest: "{{ homeassistant_secrets_tmp_repo_path }}"

- name: Copy secrets.yaml to /home/homeassistant/.homeassistant
  copy:
    src: "{{ homeassistant_secrets_tmp_repo_path }}/secrets.yaml"
    dest: "{{ dot_homeassistant_path }}"
    force: yes
  when: stat_result.stat.islnk == False

- name: Copy secrets.yaml to homeassistant symbolic link location
  copy:
    src: "{{ homeassistant_secrets_tmp_repo_path }}/secrets.yaml"
    dest: "{{ stat_result.stat.lnk_source }}"
    force: yes
  when: stat_result.stat.islnk == True

- name: Delete homeassistant_secrets repo
  file:
    path: "{{ homeassistant_secrets_tmp_repo_path }}"
    state: absent

- name: Delete home-assistant.log
  file:
    path: "{{ dot_homeassistant_path }}/home-assistant.log"
    state: absent

- name: Change owner and group of /home/homeassistant/.homeassistant to homeassistant
  file:
    path: "{{ dot_homeassistant_path }}"
    owner: homeassistant
    group: homeassistant
    recurse: yes
  when: stat_result.stat.islnk == False

- name: Change owner and group of homeassistant symbolic link location to homeassistant
  file:
    path: "{{ stat_result.stat.lnk_source }}"
    owner: homeassistant
    group: homeassistant
    recurse: yes
  when: stat_result.stat.islnk == True

- name: Restart home-assistant@homeassistant.service and enable
  service:
    name: home-assistant@homeassistant.service
    state: restarted
    enabled: yes
    daemon_reload: yes
