title: Home Assistant

views:
  - icon: mdi:home
    title: Home
    id: home
    cards:
      - title: Bedroom
        type: entities
        entities:
          - light.hue_color_spots
          - light.hue_lightstrips
          - light.xiaomi_mi_bedside_lamp
          - sensor.bedroom_sht31_smartgadget_temperature
          - sensor.bedroom_sht31_smartgadget_humidity
      - title: Contact birthdays
        type: entities
        entities:
          - calendar.contacts_birthdays
      - title: Devices
        type: entities
        entities:
          - sensor.hue_bridge_state
          - sensor.lametric_time_state
          - sensor.xiomei_mi_bedside_lamp_state
          - sensor.nokia_sleep_state
          - sensor.chromecast_2_state
          - sensor.hp_envy_5530_state
          - sensor.ryan_desktop_state
      - title: Weather
        type: entities
        entities:
          - sensor.owm_condition
          - sensor.owm_forecast
          - sensor.owm_temperature
          - sensor.owm_humidity
          - sensor.owm_rain
          - sensor.owm_wind_speed
      - title: Sun and moon
        type: entities
        entities:
          - sensor.day_night
          - sensor.sunrise
          - sensor.sunset
          - sensor.moon
      - title: Scenes
        type: entities
        entities:
          - scene.night_mode
          - scene.hue_color_spot_relax
          - scene.hue_color_spot_read
          - scene.hue_color_spot_concentrate
          - scene.hue_color_spot_energize

  - icon: mdi:desktop-classic
    title: Devices
    id: devices
    cards:
      - title: Raspbery Pi 3 B+
        type: entities
        entities:
          - sensor.xxlpitu_home_pi_cpu
          - sensor.xxlpitu_home_pi_ram
          - sensor.xxlpitu_home_pi_ssd_used
          - sensor.xxlpitu_home_pi_ssd_free
      - title: Raspbery Pi 3 B
        type: entities
        entities:
          - sensor.xxlpitu_jcrk_pi_cpu
          - sensor.xxlpitu_jcrk_pi_ram
          - sensor.xxlpitu_jcrk_pi_hdd_used
          - sensor.xxlpitu_jcrk_pi_hdd_free
      - title: JCRK Synology
        type: entities
        entities:
          - sensor.cpu_load_total
          - sensor.memory_usage_real
          - sensor.volume_used_volume_1
          - sensor.jcrk_synology_hdd_free
      - title: Battery
        type: entities
        entities:
          - sensor.bedroom_sht31_smartgadget_battery
          - sensor.hue_bedroom_dimmer_battery

  - icon: mdi:playlist-play
    title: Automations
    id: automations
    cards:
      - title: Automations
        type: entities
        entities:
          - automation.set_default_theme_at_startup
          - automation.mute_sonos_when_daniela_and_marcel_leaves_network
          - automation.notify_daily_at_600_about_weather_forcast
          - automation.notify_on_home_assistant_shutdown
          - automation.notify_on_home_assistant_start
          - automation.notify_when_home_assistant_updates_are_available
          - automation.turn_off_lights_when_ryan_leaves_network
          - input_boolean.nokia_sleep_trigger

  - icon: mdi:music-note
    title: Sonos
    id: sonos
    cards:
      - title: Sonos
        type: entities
        entities:
          - media_player.bad
          - media_player.esszimmer
          - media_player.kuche
          - media_player.schlafdraussen
          - media_player.wohnzimmer
