- name: Download get-docker.sh from get.docker.com
  become: yes
  become_user: root
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: +x

- name: Install Docker
  become: yes
  become_user: root
  shell: /tmp/get-docker.sh

- name: Add docker group
  group:
    name: docker
    state: present

# TODO fails
- name: Restart docker
  service:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes
