---
- name: Setup xxlpitu-server-home
  hosts: XXLPitu-Server-Home
  become: yes
  become_user: root
  vars_files:
    - vars/config.yaml
    - vars/vault.yaml
  roles:
    - common
    - log2ram
    - duckdns
    - portainer
    - glances
    - resilio_sync
    - tv_time_export
    - homeassistant
    - mal_export
