# TODO homeassistant use GB insted of TB

- platform: synologydsm
  host: jcrk.synology.me
  port: 5000
  username: !secret jcrk_synology_username
  password: !secret jcrk_synology_password
  ssl: false
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - volume_percentage_used
    - volume_size_total
    - volume_size_used

- platform: template
  sensors:
    # TODO homeassistant remove tb from the sensor data
    # total_size_volume_1_raw:
    #   value_template: "{{ regex_match('14TB', '[0-9]*.?[0-9]*', false) }}"
    #   # value_template: "{{ regex_replace('14Tb', 'Tb', '', false) }}"
    #   # value_template: "{{ states.sensor.total_size_volume_1 | regex_replace(string, 'Tb', '', false) }}"
    #
    # used_space_volume_1_raw:
    #   value_template: "{{ regex_replace(states(states.sensor.total_size_volume_1), 'Tb', '', false) }}"

    jcrk_synology_hdd_free:
      friendly_name: HDD used
      # value_template: "{{ sensor.total_size_volume_1_raw - sensor.used_space_volume_1_raw }}"
      value_template: "{{ states('sensor.used_space_volume_1') }}"
      icon_template: mdi:harddisk
      # unit_of_measurement: Tb
