- platform: openweathermap
  api_key: !secret openweathermap_api_key
  forecast: true
  language: en
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - humidity
    - clouds
    - rain

- platform: darksky
  api_key: !secret darksky_api_key
  units: ca
  update_interval: "00:15"
  monitored_conditions:
    - hourly_summary
    - temperature_low
    - temperature_high
