- platform: rest
  resource: http://localhost:61209/api/2/fs
  name: XXLPitu JCRK Pi HDD used
  value_template: >
    {% for fs in value_json %}
      {% if fs.mnt_point == "/media/WD_RED" %}
        {{ fs.percent }}
      {% endif %}
    {% endfor %}
  unit_of_measurement: "%"
  force_update: true

- platform: rest
  resource: http://localhost:61209/api/2/fs
  name: XXLPitu JCRK Pi HDD free
  value_template: >
    {% for fs in value_json %}
      {% if fs.mnt_point == "/media/WD_RED" %}
        {{ (fs.free | float / 1073741824) | round(1) }}
      {% endif %}
    {% endfor %}
  unit_of_measurement: GB
  force_update: true

- platform: rest
  resource: http://localhost:61209/api/2/cpu
  name: XXLPitu JCRK Pi CPU
  value_template: "{{ value_json.total }}"
  unit_of_measurement: "%"
  force_update: true

- platform: rest
  resource: http://localhost:61209/api/2/mem
  name: XXLPitu JCRK Pi Ram
  value_template: "{{ value_json.percent }}"
  unit_of_measurement: "%"
  force_update: true
