---
- name: Delete Absolute-Series-Scanner temp dir
  file:
    path: "{{ absolute_series_scanner_tmp_path }}"
    state: absent

- name: Clone Absolute-Series-Scanner to temp dir
  git:
    repo: https://github.com/ZeroQI/Absolute-Series-Scanner.git
    dest: "{{ absolute_series_scanner_tmp_path }}"

- name: Create plex /Scanners dir
  file:
    path: "{{ plex_data_path }}/Scanners"
    state: directory

- name: Create plex /Scanners/Series dir
  file:
    path: "{{ plex_data_path }}/Scanners/Series"
    state: directory

# TODO use copy module
- name: Copy "Absolute Series Scanner.py" to plex Scanners/Series path
  command: "cp '{{ absolute_series_scanner_tmp_path }}/Scanners/Series/Absolute Series Scanner.py' '{{ plex_data_path }}/Scanners/Series'"
