---
- name: Delete Absolute-Series-Scanner temp dir
  file:
    path: "{{ plex.tmp_absolute_series_scanner_path }}"
    state: absent

- name: Clone Absolute-Series-Scanner to temp dir
  git:
    repo: https://github.com/ZeroQI/Absolute-Series-Scanner.git
    dest: "{{ plex.tmp_absolute_series_scanner_path }}"

- name: Create plex /Scanners dir
  file:
    path: "{{ data_path.library.plex.main }}/Scanners"
    state: directory

- name: Create plex /Scanners/Series dir
  file:
    path: "{{ data_path.library.plex.main }}/Scanners/Series"
    state: directory

- name: Copy "Absolute Series Scanner.py" to plex Scanners/Series path
  synchronize:
    src: "{{ plex.tmp_absolute_series_scanner_path }}/Scanners/Series/Absolute Series Scanner.py"
    dest: "{{ data_path.library.plex.main }}/Scanners/Series/Absolute Series Scanner.py"
  delegate_to: "{{ inventory_hostname }}"
