---
- name: Create resilio sync dir
  file:
    path: "{{ resilio_sync_save_path }}"
    state: directory

- name: Create resilio sync Downloads dir
  file:
    path: "{{ resilio_sync_downloads_save_path }}"
    state: directory

- name: Create resilio sync data dir
  file:
    path: "{{ resilio_sync_data_path }}"
    state: directory

- name: Delete resilio sync docker-compose dir
  file:
    path: "{{ docker_compose_resilio_sync_path }}"
    state: absent

- name: Create resilio sync docker-compose dir
  file:
    path: "{{ docker_compose_resilio_sync_path }}"
    state: directory

- name: Copy Dockerfile to resilio sync docker-compose dir
  copy:
    src: "{{ role_path }}/files/Dockerfile"
    dest: "{{ docker_compose_resilio_sync_path }}"
    force: yes

- name: Generate docker-compose.yaml with correct values
  template:
    src: docker-compose.yaml.jinja2
    dest: "{{ docker_compose_resilio_sync_path }}/docker-compose.yaml"

- name: Generate myanimelist-export.yaml with correct values
  template:
    src: config.json.jinja2
    dest: "{{ docker_compose_resilio_sync_path }}/config.json"

- name: docker-compose up
  command: docker-compose up --build --detach --force-recreate
  args:
    chdir: "{{ docker_compose_resilio_sync_path }}"
