# TODO add tv_time_export export dir to sync dir

- name: Build resilio-sync image
  docker_image:
    name: linuxserver/resilio-sync

- name: Create resilio sync dir
  file:
    path: "{{ resilio_sync_save_path }}"
    state: directory

- name: Create resilio sync Downloads dir
  file:
    path: "{{ resilio_sync_downloads_save_path }}"
    state: directory

- name: Create resilio sync data dir
  file:
    path: "{{ resilio_sync_data_path }}"
    state: directory

- name: Delete resilio-sync container
  shell: docker rm --force resilio-sync
  ignore_errors: yes

- name: Create resilio-sync container
  shell: >-
    docker run
    --detach
    --env TZ='{{ timezone }}'
    --mount src='{{ resilio_sync_data_path }}',target=/config,type=bind
    --mount src='{{ resilio_sync_downloads_save_path }}',target=/downloads,type=bind
    --mount src='{{ resilio_sync_save_path }}',target=/sync,type=bind
    --name resilio-sync
    --publish 5555:5555
    --publish 8888:8888
    --restart unless-stopped
    linuxserver/resilio-sync
