---
# plex
symbolic_link_plex_data_path: "{{ main_drive_path }}/library/plex-data/Plex Media Server/"
plex_data_path: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server

# tautulli
tautulli_repo_path: /opt/Tautulli
tautulli_data_path: "{{ main_drive_path }}/library/Tautulli-data"

# plex addons
plex_plugins_path: "{{ plex_data_path }}/Plug-ins"

# Absolute-Series-Scanner
absolute_series_scanner_tmp_path: /tmp/Absolute-Series-Scanner

# Subliminal plugin
subliminal_plugin_path: "{{ plex_plugins_path }}/Subliminal.bundle"

# OpenMovieDatabase plugin
open_movie_database_plugin_path: "{{ plex_plugins_path }}/OpenMovieDatabase.bundle"
